// The file is generated by build.sh; DO NOT EDIT!
if (scene_name == "dragon_in_box") {
	#include "dragon_in_box.scene"
} else if (scene_name == "dragon_under_distantlight") {
	#include "dragon_under_distantlight.scene"
} else if (scene_name == "dragon_under_spotlight") {
	#include "dragon_under_spotlight.scene"
} else if (scene_name == "earth_in_box") {
	#include "earth_in_box.scene"
} else if (scene_name == "girl_in_box") {
	#include "girl_in_box.scene"
} else if (scene_name == "glass_in_box") {
	#include "glass_in_box.scene"
} else if (scene_name == "house") {
	#include "house.scene"
} else if (scene_name == "simple_room") {
	#include "simple_room.scene"
} else if (scene_name == "sphere_in_box") {
	#include "sphere_in_box.scene"
} else 
	throw std::invalid_argument("scene not found");
