#!/usr/bin/env bash

echo "// The file is generated by build.sh; DO NOT EDIT!" > all_scenes.hpp

first=1

for scene in *.scene; do
    echo -ne "if (scene_name == \"${scene%.*}\") {\n\t#include \"$scene\"\n} else " >> all_scenes.hpp 
done
echo -e '\n\tthrow std::invalid_argument("scene not found");' >> all_scenes.hpp
